// <auto-generated />
using System;
using Database.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ContextDatabase))]
    [Migration("20230601223430_CreacionTablas")]
    partial class CreacionTablas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Database.Models.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PedidoId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("Direccion");

                    b.Property<DateTime>("Entrega")
                        .HasColumnType("datetime2")
                        .HasColumnName("Entrega");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("NombreCliente");

                    b.Property<int>("PedidoEstadoId")
                        .HasColumnType("int")
                        .HasColumnName("PedidoEstadoId");

                    b.HasKey("PedidoId");

                    b.HasIndex("PedidoEstadoId");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("Database.Models.PedidoEstado", b =>
                {
                    b.Property<int>("PedidoEstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PedidoEstadoId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("Nombre");

                    b.HasKey("PedidoEstadoId");

                    b.ToTable("PedidoEstado");

                    b.HasData(
                        new
                        {
                            PedidoEstadoId = 1,
                            Nombre = "Ingresado"
                        },
                        new
                        {
                            PedidoEstadoId = 2,
                            Nombre = "En procesamiento"
                        },
                        new
                        {
                            PedidoEstadoId = 3,
                            Nombre = "Despachado"
                        },
                        new
                        {
                            PedidoEstadoId = 4,
                            Nombre = "Entregado"
                        });
                });

            modelBuilder.Entity("Database.Models.Pedido", b =>
                {
                    b.HasOne("Database.Models.PedidoEstado", "PedidoEstado")
                        .WithMany("Pedidos")
                        .HasForeignKey("PedidoEstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PedidoEstado");
                });

            modelBuilder.Entity("Database.Models.PedidoEstado", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
